#!/usr/bin/env bash
# agents/dev/sandbox/entrypoint.sh
set -euo pipefail

# ─── Обязательные env (передаются из runner.py через docker run -e) ─
: "${TASK_ID:?TASK_ID required}"
: "${BRANCH_NAME:?BRANCH_NAME required}"           # уже транслитерирован в runner.py
: "${REPO_URL:?REPO_URL required}"                 # https://x-access-token:${GITHUB_TOKEN}@github.com/...
: "${ANTHROPIC_API_KEY:?ANTHROPIC_API_KEY required}"
: "${GITHUB_TOKEN:?GITHUB_TOKEN required}"
: "${BASE_BRANCH:=main}"
: "${MAX_TURNS:=50}"
: "${CLAUDE_MODEL:=claude-sonnet-4-6}"

# ─── Прокси из baked-в-образ если задан ──────────────────────
if [[ -n "${BAKED_PROXY_URL:-}" ]]; then
  export HTTPS_PROXY="${BAKED_PROXY_URL}"
  export HTTP_PROXY="${BAKED_PROXY_URL}"
  export NO_PROXY="github.com,api.github.com,objects.githubusercontent.com,raw.githubusercontent.com"
  echo "[sandbox] Using baked proxy: ${BAKED_PROXY_URL}"
fi

# ─── gh auth ─────────────────────────────────────────────────
# gh CLI автоматически использует GITHUB_TOKEN из env (gh auth login падает если token уже set)
# Проверим что у gh есть доступ к API:
gh auth status 2>&1 | head -5 || echo "[sandbox] gh auth status non-zero, but GITHUB_TOKEN is set — proceeding"

# ─── Клон ────────────────────────────────────────────────────
WORK=/workspace/repo
echo "[sandbox] Cloning ${REPO_URL##*@} branch=${BASE_BRANCH}"
git clone --depth 50 --branch "${BASE_BRANCH}" "${REPO_URL}" "${WORK}"
cd "${WORK}"

# Создаём ветку (имя уже валидное ASCII)
git checkout -b "${BRANCH_NAME}"

# ─── TASK.md и CLAUDE.md уже примонтированы как :ro в /workspace/task/ ───
if [[ ! -f /workspace/task/TASK.md ]]; then
  echo "[sandbox] FATAL: /workspace/task/TASK.md missing"
  exit 2
fi

# НЕ копируем CLAUDE.md в корень репо — это перезатёрло бы реальный CLAUDE.md проекта.
# Role-rules инлайнятся внутри TASK.md (см. runner.py:_build_task_md).
# Claude Code прочитает существующий CLAUDE.md / PROJECT.md в репо как контекст проекта.

# ─── Запуск Claude Code ──────────────────────────────────────
echo "[sandbox] Running Claude Code (model=${CLAUDE_MODEL}, max_turns=${MAX_TURNS})"
TASK_CONTENT="$(cat /workspace/task/TASK.md)"

# claude code в non-interactive режиме
claude \
  --model "${CLAUDE_MODEL}" \
  --max-turns "${MAX_TURNS}" \
  --dangerously-skip-permissions \
  -p "${TASK_CONTENT}" \
  > /workspace/task/claude-output.log 2>&1 || {
  CC_EXIT=$?
  echo "[sandbox] Claude Code exited with ${CC_EXIT}"
  # продолжаем — может что-то закоммитил
}

# ─── Финализация: Claude Code мог уже сам сделать commit/push/PR ─────────
# Наша задача — синхронизироваться: doostage остатки, при нужде commit/push/PR,
# и в любом случае правильно сообщить boту что произошло.
cd "${WORK}"

# 1) Stage всё что Claude забыл add'ить (он мог отредачить файлы но не git add'ить)
git add -A 2>/dev/null || true

# 2) Если staged есть — делаем коммит
if ! git diff --cached --quiet; then
  git commit -m "$(cat <<EOF
feat(${TASK_ID}): automated changes from dev agent

Task: ${TASK_ID}
Generated by exec-team dev-agent in sandbox.
EOF
)" || true
fi

# 3) Сколько коммитов поверх base branch (= результат работы Claude или нас)?
COMMITS_AHEAD=$(git rev-list --count "origin/${BASE_BRANCH}..HEAD" 2>/dev/null || echo "0")

if [[ "${COMMITS_AHEAD}" == "0" ]]; then
  echo "[sandbox] No commits on branch — nothing to ship"
  echo "NO_CHANGES" > /workspace/task/result.txt
  exit 0
fi

echo "[sandbox] ${COMMITS_AHEAD} commit(s) on branch ${BRANCH_NAME}"

# 4) Push — идемпотентно. Если Claude уже push'ил, тут просто 'Everything up-to-date'.
git push -u origin "${BRANCH_NAME}" 2>&1 || true

# 5) Существует ли уже PR для этой ветки (Claude мог открыть)?
PR_URL="$(gh pr view "${BRANCH_NAME}" --json url --jq .url 2>/dev/null || true)"

if [[ -z "${PR_URL}" ]]; then
  # Нет PR — создаём
  PR_BODY_FILE=/workspace/task/pr-body.md
  if [[ ! -f "${PR_BODY_FILE}" ]]; then
    echo "Automated PR from exec-team dev-agent for task ${TASK_ID}." > "${PR_BODY_FILE}"
  fi
  TITLE_RAW="$(head -1 /workspace/task/TASK.md 2>/dev/null | sed 's/^# *//')"
  TITLE_RAW="${TITLE_RAW:-Task ${TASK_ID}}"
  CREATE_OUT="$(gh pr create \
    --base "${BASE_BRANCH}" \
    --head "${BRANCH_NAME}" \
    --title "[${TASK_ID:0:8}] ${TITLE_RAW}" \
    --body-file "${PR_BODY_FILE}" 2>&1 || true)"
  # gh pr create при success печатает URL, при error — текст с URL существующего PR
  PR_URL="$(echo "${CREATE_OUT}" | grep -oE 'https://github\.com/[^[:space:]]+/pull/[0-9]+' | head -1)"
fi

if [[ -n "${PR_URL}" ]]; then
  echo "${PR_URL}" > /workspace/task/pr-url.txt
  echo "[sandbox] PR: ${PR_URL}"
  exit 0
else
  echo "[sandbox] Could not determine PR URL — but commits are pushed to ${BRANCH_NAME}"
  echo "BRANCH_PUSHED_NO_PR" > /workspace/task/result.txt
  exit 0
fi
