#!/usr/bin/env bash
# agents/dev/sandbox/entrypoint.sh
set -euo pipefail

# ─── Обязательные env (передаются из runner.py через docker run -e) ─
: "${TASK_ID:?TASK_ID required}"
: "${BRANCH_NAME:?BRANCH_NAME required}"           # уже транслитерирован в runner.py
: "${REPO_URL:?REPO_URL required}"                 # https://x-access-token:${GITHUB_TOKEN}@github.com/...
: "${ANTHROPIC_API_KEY:?ANTHROPIC_API_KEY required}"
: "${GITHUB_TOKEN:?GITHUB_TOKEN required}"
: "${BASE_BRANCH:=main}"
: "${MAX_TURNS:=50}"
: "${CLAUDE_MODEL:=claude-sonnet-4-6}"

# ─── Прокси из baked-в-образ если задан ──────────────────────
if [[ -n "${BAKED_PROXY_URL:-}" ]]; then
  export HTTPS_PROXY="${BAKED_PROXY_URL}"
  export HTTP_PROXY="${BAKED_PROXY_URL}"
  export NO_PROXY="github.com,api.github.com,objects.githubusercontent.com,raw.githubusercontent.com"
  echo "[sandbox] Using baked proxy: ${BAKED_PROXY_URL}"
fi

# ─── gh auth ─────────────────────────────────────────────────
echo "${GITHUB_TOKEN}" | gh auth login --with-token

# ─── Клон ────────────────────────────────────────────────────
WORK=/workspace/repo
echo "[sandbox] Cloning ${REPO_URL##*@} branch=${BASE_BRANCH}"
git clone --depth 50 --branch "${BASE_BRANCH}" "${REPO_URL}" "${WORK}"
cd "${WORK}"

# Создаём ветку (имя уже валидное ASCII)
git checkout -b "${BRANCH_NAME}"

# ─── TASK.md и CLAUDE.md уже примонтированы как :ro в /workspace/task/ ───
if [[ ! -f /workspace/task/TASK.md ]]; then
  echo "[sandbox] FATAL: /workspace/task/TASK.md missing"
  exit 2
fi

# Копируем CLAUDE.md в корень репозитория для Claude Code
if [[ -f /workspace/task/CLAUDE.md ]]; then
  cp /workspace/task/CLAUDE.md "${WORK}/CLAUDE.md"
fi

# ─── Запуск Claude Code ──────────────────────────────────────
echo "[sandbox] Running Claude Code (model=${CLAUDE_MODEL}, max_turns=${MAX_TURNS})"
TASK_CONTENT="$(cat /workspace/task/TASK.md)"

# claude code в non-interactive режиме
claude \
  --model "${CLAUDE_MODEL}" \
  --max-turns "${MAX_TURNS}" \
  --dangerously-skip-permissions \
  -p "${TASK_CONTENT}" \
  > /workspace/task/claude-output.log 2>&1 || {
  CC_EXIT=$?
  echo "[sandbox] Claude Code exited with ${CC_EXIT}"
  # продолжаем — может что-то закоммитил
}

# ─── Проверяем были ли изменения ─────────────────────────────
cd "${WORK}"
git add -A

if git diff --cached --quiet; then
  echo "[sandbox] No changes were made by Claude Code"
  echo "NO_CHANGES" > /workspace/task/result.txt
  exit 0
fi

git commit -m "$(cat <<EOF
feat(${TASK_ID}): automated changes from dev agent

Task: ${TASK_ID}
Generated by exec-team dev-agent in sandbox.
EOF
)"

# ─── Пуш и открытие PR ───────────────────────────────────────
git push -u origin "${BRANCH_NAME}"

PR_BODY_FILE=/workspace/task/pr-body.md
if [[ ! -f "${PR_BODY_FILE}" ]]; then
  echo "Automated PR from exec-team dev-agent for task ${TASK_ID}." > "${PR_BODY_FILE}"
fi

PR_URL="$(gh pr create \
  --base "${BASE_BRANCH}" \
  --head "${BRANCH_NAME}" \
  --title "[${TASK_ID}] $(head -1 /workspace/task/TASK.md | sed 's/^# *//')" \
  --body-file "${PR_BODY_FILE}")"

echo "${PR_URL}" > /workspace/task/pr-url.txt
echo "[sandbox] PR opened: ${PR_URL}"
exit 0
